# Generated by Django 5.1.6 on 2025-02-12 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
    ]
