# Generated by Django 5.1.6 on 2025-02-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('processed', 'Processed'), ('in_session', 'In_session'), ('done', 'Done')], default='sent', max_length=50),
        ),
    ]
