# Generated by Django 5.1.6 on 2025-02-17 22:03

import django.db.models.deletion
import session.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0004_alter_appointment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('started', 'Started'), ('ended', 'Ended')], default='started', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointment.appointment')),
                ('users', models.ManyToManyField(related_name='doctor_session', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorSessionMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('type', models.CharField(choices=[('text', 'Text'), ('notification', 'Notification'), ('image', 'Image'), ('video', 'Video')], default='text', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/chat_images/', validators=[session.models.validate_file])),
                ('video', models.FileField(blank=True, null=True, upload_to='media/chat_videos/', validators=[session.models.validate_file])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentmessages', to=settings.AUTH_USER_MODEL)),
                ('doctor_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='session.doctorsession')),
            ],
        ),
        migrations.CreateModel(
            name='Medications',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('weight', models.CharField(max_length=10)),
                ('dosage', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('has_reminder', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_by', to=settings.AUTH_USER_MODEL)),
                ('created_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications_for', to=settings.AUTH_USER_MODEL)),
                ('doctor_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='session.doctorsession')),
            ],
        ),
    ]
