# Generated by Django 5.1.6 on 2025-02-24 19:52

import session.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorsessionmessage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='doctorsessionmessage',
            name='video',
        ),
        migrations.AddField(
            model_name='doctorsessionmessage',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='media/chat_files/', validators=[session.models.validate_file]),
        ),
        migrations.AlterField(
            model_name='doctorsessionmessage',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('notification', 'Notification'), ('file', 'File')], default='text', max_length=50),
        ),
    ]
