# Generated by Django 5.1.6 on 2025-02-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_remove_doctorsessionmessage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsessionmessage',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('notification', 'Notification'), ('image', 'Image'), ('video', 'Video')], default='text', max_length=50),
        ),
    ]
